'use client';

import { useState, useEffect } from 'react';
import { ArenaFrame } from './ArenaFrame';

export interface RoundIntro {
  eyebrow: string;
  title: string;
  lines: string[];
}

export interface RoundOutro {
  eyebrow: string;
  fact: string;
  source?: string;
}

export const ROUND_INTROS: Record<1 | 2 | 3, RoundIntro> = {
  1: {
    eyebrow: 'ROUND 1 OF 3',
    title: 'Real or AI?',
    lines: [
      'You get 3 images, one at a time.',
      '{n} seconds each — decide if it was taken by a person or generated by AI.',
      "You won't be told if you were right. Scores tally at the end.",
    ],
  },
  2: {
    eyebrow: 'ROUND 2 OF 3',
    title: 'Draw vs AI',
    lines: [
      "You'll be given one object to draw.",
      '{n} seconds, using your finger on the touch canvas.',
      'The AI neural network only inspects after you hit submit.',
    ],
  },
  3: {
    eyebrow: 'ROUND 3 OF 3',
    title: 'You vs AIDA',
    lines: [
      'One official AI trivia question.',
      '{n} seconds to drag the slider to your best estimate.',
      'Closer guesses score higher. Everyone today answers the same prompt.',
    ],
  },
};

export const ROUND_OUTROS: Record<1 | 2 | 3, RoundOutro> = {
  1: {
    eyebrow: 'ROUND 1 COMPLETE',
    fact:
      'Most people score close to chance on recent AI images. The tells we all learned — extra fingers, warped text, waxy skin — are the exact flaws each new model generation fixes first.',
  },
  2: {
    eyebrow: 'ROUND 2 COMPLETE',
    fact:
      'That neural network ran entirely on your device with TensorFlow.js. Zero server delay — trained on millions of human doodles and shrunk to under one megabyte.',
  },
  3: {
    eyebrow: 'ALL ROUNDS COMPLETE',
    fact: 'Transmitting final score and compiling leaderboard ranking…',
  },
};

export function Interstitial({
  intro,
  outro,
  seconds = 7,
  timerValue,
  onDone,
}: {
  intro?: RoundIntro;
  outro?: RoundOutro;
  seconds?: number;
  timerValue?: number;
  onDone: () => void;
}) {
  const [remaining, setRemaining] = useState(seconds);

  useEffect(() => {
    if (remaining <= 0) {
      onDone();
      return;
    }
    const t = setTimeout(() => setRemaining((r) => r - 1), 1000);
    return () => clearTimeout(t);
  }, [remaining, onDone]);

  const content = intro ?? outro;
  if (!content) return null;

  const isIntro = Boolean(intro);

  return (
    <ArenaFrame>
      <div className="flex flex-1 flex-col justify-center">
        {/* Eyebrow badge */}
        <div className="text-center">
          <span className="inline-block rounded-md border border-cyan-500/40 bg-cyan-950/40 px-3 py-1 font-pixel text-[9px] uppercase tracking-widest text-cyan-300 shadow-[0_0_12px_rgba(0,240,255,0.2)]">
            {content.eyebrow}
          </span>
        </div>

        {/* Content Card */}
        <div className="pixel-box mt-4 p-6 sm:p-8">
          {isIntro && intro ? (
            <>
              <h1 className="font-display text-2xl font-black uppercase tracking-wide text-white drop-shadow-[0_2px_8px_rgba(0,0,0,0.9)] sm:text-3xl text-center">
                {intro.title}
              </h1>

              <ul className="mt-6 space-y-3.5">
                {intro.lines.map((line, i) => (
                  <li key={i} className="flex items-start gap-3 text-sm leading-relaxed text-slate-200">
                    <span className="mt-1 font-pixel text-xs text-cyan-400">▶</span>
                    <span className="font-display">
                      {timerValue != null
                        ? line.replace('{n}', String(timerValue))
                        : line.replace('{n}', '')}
                    </span>
                  </li>
                ))}
              </ul>
            </>
          ) : (
            outro && (
              <div className="text-center">
                <div className="mb-4 inline-flex h-12 w-12 items-center justify-center rounded-full bg-cyan-500/20 text-cyan-400">
                  <span className="font-pixel text-xl">💡</span>
                </div>
                <p className="font-display text-base font-semibold leading-relaxed text-slate-200 sm:text-lg">
                  {outro.fact}
                </p>
              </div>
            )
          )}
        </div>
      </div>

      {/* Button */}
      <div className="mt-6">
        <button
          onClick={onDone}
          className="pixel-btn pixel-btn-cyan min-h-[64px] w-full text-sm"
        >
          <span>{isIntro ? "I'M READY" : 'CONTINUE'}</span>
          <span className="tabular font-pixel ml-2 opacity-70">({remaining}s)</span>
        </button>
        <p className="mt-3 text-center font-display text-xs text-slate-400">
          This briefing is not timed. Your round timer only counts during active gameplay.
        </p>
      </div>
    </ArenaFrame>
  );
}
