'use client';

import { useState, useEffect } from 'react';
import { AnimatedSprite, PxButton, PxChip, PxPanel, Scene, Wordmark } from '@/components/px';

export interface RoundIntro {
  eyebrow: string;
  title: string;
  lines: string[];
}

export interface RoundOutro {
  eyebrow: string;
  title?: string;
  fact: string;
  tagline?: string;
}

export const ROUND_INTROS: Record<1 | 2 | 3, RoundIntro> = {
  1: {
    eyebrow: 'ROUND 1 OF 3',
    title: 'Spot the Fake',
    lines: [
      'You get images, one at a time.',
      '{n} seconds each — decide if it is a real photo or generated by AI.',
      "You won't be told if you were right during the game. All scores come at the end.",
    ],
  },
  2: {
    eyebrow: 'ROUND 2 OF 3',
    title: 'Draw vs AI',
    lines: [
      "You'll be given one target object to draw.",
      '{n} seconds on the grid using your finger or mouse.',
      'Our on-device AI will analyze your drawing live when you submit.',
    ],
  },
  3: {
    eyebrow: 'ROUND 3 OF 3',
    title: 'You vs AIDA',
    lines: [
      'One challenge question for today.',
      '{n} seconds to drag the slider to your best guess.',
      'The closer your guess to the exact value, the higher you score.',
    ],
  },
};

export const ROUND_OUTROS: Record<1 | 2 | 3, RoundOutro> = {
  1: {
    eyebrow: 'ROUND 1 COMPLETE',
    title: 'FUN FACT',
    fact:
      'AI mistakes are no longer limited to extra fingers... the hardest clues can be inconsistent reflections, lighting or text.',
    tagline: 'SAME MINDS. DIFFERENT POSSIBILITIES. A BRIGHTER TOMORROW.',
  },
  2: {
    eyebrow: 'ROUND 2 COMPLETE',
    title: 'FUN FACT',
    fact:
      'Our model was trained with approximately 300,000 human doodles across 15 drawing categories. You will learn how to do so in your PDAII and ML courses.',
    tagline: 'SAME MINDS. DIFFERENT POSSIBILITIES. A BRIGHTER TOMORROW.',
  },
  3: {
    eyebrow: 'ALL ROUNDS COMPLETE',
    title: 'FINAL SCORING',
    fact: 'Scoring your challenge performance and tallying the leaderboard…',
    tagline: 'CREATIVITY STILL WINS.',
  },
};

export function Interstitial({
  intro,
  outro,
  seconds = 7,
  timerValue,
  onDone,
}: {
  intro?: RoundIntro;
  outro?: RoundOutro;
  seconds?: number;
  timerValue?: number;
  onDone: () => void;
}) {
  const [remaining, setRemaining] = useState(seconds);

  useEffect(() => {
    if (remaining <= 0) {
      onDone();
      return;
    }
    const t = setTimeout(() => setRemaining((r) => r - 1), 1000);
    return () => clearTimeout(t);
  }, [remaining, onDone]);

  const content = intro ?? outro;
  if (!content) return null;
  const isIntro = Boolean(intro);
  const round = intro ? ROUND_BY_TITLE[intro.title] : outro ? ROUND_BY_EYEBROW[outro.eyebrow] : 1;
  const art = ROUND_ART[round];

  return (
    <Scene left={art.left} right={art.right} leftWidth="30vw" rightWidth="30vw">
      <div className="mx-auto flex w-full max-w-[520px] flex-1 flex-col px-4 pb-6 pt-5 sm:px-6">
        <div className="flex justify-center">
          <PxChip className="text-[9px] sm:text-[10px]">{content.eyebrow}</PxChip>
        </div>

        <div className="my-auto flex flex-col items-center py-5 text-center">
          {isIntro && intro && (
            <>
              <Wordmark name={art.wordmark} priority className="w-[86%] max-w-[420px]" />
              <div className="mt-4 flex items-end gap-3">
                <AnimatedSprite name={art.human} className="h-24 sm:h-28" />
                <AnimatedSprite name={art.robot} speed="1.3s" className="h-24 drop-shadow-[0_0_14px_rgba(0,187,252,0.5)] sm:h-28" />
              </div>
              <PxPanel tone="cyan" className="mt-4 w-full px-5 py-5 text-left">
                <ul className="space-y-3">
                  {intro.lines.map((line, i) => (
                    <li key={i} className="flex items-start gap-3 text-[16px] leading-snug text-[#dff6ff]">
                      <span className="mt-1.5 h-3 w-3 shrink-0 bg-[#7ffafe] shadow-[0_0_6px_#7ffafe]" aria-hidden="true" />
                      <span>{line.replace('{n}', timerValue != null ? String(timerValue) : '')}</span>
                    </li>
                  ))}
                </ul>
              </PxPanel>
            </>
          )}

          {!isIntro && outro && (
            <>
              <h2 className="font-px text-[22px] text-[#ffe66a] px-text-outline sm:text-[26px]">{outro.title ?? 'FUN FACT'}</h2>
              <div className="relative mt-4 w-full">
                <AnimatedSprite name="mascot-girl-cheer" speed="0.8s" className="absolute -top-10 left-2 z-10 h-32 sm:-left-2 sm:h-40" />
                <PxPanel tone="gold" className="w-full py-5 pl-[38%] pr-5 text-left sm:pl-[36%]">
                  <p className="text-[17px] leading-snug text-[#f4f6ff] sm:text-[18px]">{outro.fact}</p>
                </PxPanel>
              </div>
              {outro.tagline && (
                <p className="mt-4 font-px text-[7px] leading-relaxed text-[#7ffafe] sm:text-[8px]">{outro.tagline}</p>
              )}
            </>
          )}
        </div>

        <div>
          <PxButton onClick={onDone} className="min-h-[64px] w-full text-[14px]">
            {isIntro ? "I'M READY" : 'NEXT ROUND →'}
            <span className="tabular text-[10px] opacity-70">({remaining}s)</span>
          </PxButton>
          <p className="mt-2 text-center font-px text-[7px] text-[#9fb3e6]">THIS SCREEN IS NOT TIMED AGAINST YOUR SCORE.</p>
        </div>
      </div>
    </Scene>
  );
}

const ROUND_BY_TITLE: Record<string, 1 | 2 | 3> = { 'Spot the Fake': 1, 'Draw vs AI': 2, 'You vs AIDA': 3 };
const ROUND_BY_EYEBROW: Record<string, 1 | 2 | 3> = { 'ROUND 1 COMPLETE': 1, 'ROUND 2 COMPLETE': 2, 'ALL ROUNDS COMPLETE': 3 };

const ROUND_ART = {
  1: { wordmark: 'real-or-ai', left: 'r1-left', right: 'r1-right', human: 'emirati-boy', robot: 'robot-1' },
  2: { wordmark: 'draw-vs-ai', left: 'r2-left', right: 'r2-right', human: 'girl-purple-hijab', robot: 'robot-arms-raised' },
  3: { wordmark: 'ai-knowledge', left: 'r3-left', right: 'r3-right', human: 'emirati-boy-confused', robot: 'robot-smirking' },
} as const;
