'use client';

import { useState, useEffect, useRef, useCallback } from 'react';
import type { Round1Slot } from '@/types';

/**
 * Round 1 — Real or AI?
 *
 * Three images, one at a time. §11 forbids telling the student whether they
 * were right, so the only feedback is a neutral "Answer locked". That is a
 * deliberate product choice: without it, the first group through the booth
 * would leak the answer key to everyone behind them.
 */
export function Round1({
  attemptId,
  slots,
  msPerImage,
  onComplete,
}: {
  attemptId: string;
  slots: Round1Slot[];
  msPerImage: number;
  onComplete: () => void;
}) {
  const pending = slots.filter((s) => !s.answered);
  const [index, setIndex] = useState(0);
  const [locked, setLocked] = useState(false);
  const [remaining, setRemaining] = useState(msPerImage);
  const startedAt = useRef(Date.now());
  const submitting = useRef(false);

  const current = pending[index];

  const submit = useCallback(
    async (answer: 'real' | 'ai_generated' | null) => {
      if (submitting.current || !current) return;
      submitting.current = true;
      setLocked(true);

      const responseTimeMs = Date.now() - startedAt.current;

      // A timeout still posts, as a wrong answer, so the slot is never left
      // unanswered and the total always adds up.
      await fetch('/api/round1/answer', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          attemptId,
          slot: current.slot,
          selectedAnswer: answer ?? 'real',
          responseTimeMs,
          idempotencyKey: crypto.randomUUID(),
        }),
      }).catch(() => {});

      setTimeout(() => {
        submitting.current = false;
        if (index + 1 >= pending.length) {
          onComplete();
        } else {
          setIndex((i) => i + 1);
          setLocked(false);
          setRemaining(msPerImage);
          startedAt.current = Date.now();
        }
      }, 700);
    },
    [attemptId, current, index, pending.length, msPerImage, onComplete],
  );

  // Countdown. Auto-submits when it runs out so a distracted student cannot
  // stall the queue behind them.
  useEffect(() => {
    if (locked) return;
    const tick = setInterval(() => {
      const elapsed = Date.now() - startedAt.current;
      const left = msPerImage - elapsed;
      setRemaining(left);
      if (left <= 0) submit(null);
    }, 100);
    return () => clearInterval(tick);
  }, [locked, msPerImage, submit]);

  if (!current) return null;

  const progress = Math.max(0, Math.min(1, remaining / msPerImage));
  const seconds = Math.max(0, Math.ceil(remaining / 1000));

  return (
    <main className="flex min-h-dvh flex-col px-5 py-6">
      <div className="mx-auto flex w-full max-w-md flex-1 flex-col">
        <div className="flex items-center justify-between text-sm">
          <span className="text-[var(--color-muted)]">
            Image {index + 1} of {pending.length}
          </span>
          <span className="tabular font-bold text-[var(--color-cyan)]">{seconds}s</span>
        </div>

        <div
          className="mt-2 h-1 w-full overflow-hidden rounded-full bg-[var(--color-edge)]"
          role="progressbar"
          aria-valuemin={0}
          aria-valuemax={100}
          aria-valuenow={Math.round(progress * 100)}
        >
          <div
            className="h-full bg-[var(--color-cyan)] transition-[width] duration-100 ease-linear"
            style={{ width: `${progress * 100}%` }}
          />
        </div>

        <h1 className="mt-6 text-center text-2xl font-bold">Real or AI?</h1>

        <div className="relative mt-5 aspect-square w-full overflow-hidden rounded-2xl border border-[var(--color-edge)] bg-[var(--color-navy)]">
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img
            src={current.storagePath}
            alt="Is this photograph real or generated by AI?"
            className="h-full w-full object-cover"
            draggable={false}
          />
          {locked && (
            <div className="absolute inset-0 flex items-center justify-center bg-[var(--color-void)]/85">
              <p className="text-xl font-bold tracking-wide text-[var(--color-cyan)]">
                Answer locked
              </p>
            </div>
          )}
        </div>

        <div className="mt-6 grid grid-cols-2 gap-3">
          <button
            onClick={() => submit('real')}
            disabled={locked}
            className="min-h-[64px] rounded-xl border border-[var(--color-edge)] bg-[var(--color-surface)] text-base font-semibold transition-colors hover:border-[var(--color-cyan)] disabled:opacity-40"
          >
            Real
          </button>
          <button
            onClick={() => submit('ai_generated')}
            disabled={locked}
            className="min-h-[64px] rounded-xl border border-[var(--color-edge)] bg-[var(--color-surface)] text-base font-semibold transition-colors hover:border-[var(--color-cyan)] disabled:opacity-40"
          >
            AI generated
          </button>
        </div>

        <p className="mt-4 text-center text-xs text-[var(--color-muted)]">
          Your total score comes at the end.
        </p>
      </div>
    </main>
  );
}
