/**
 * Loads the Round 1 image bank from a local folder into Supabase Storage.
 *
 * Content is the deadline risk on this project, not code. This exists so
 * loading forty images is one command rather than forty manual uploads, and so
 * the checks that matter — balance, file size, missing explanations — happen
 * before the fair rather than during it.
 *
 * FOLDER LAYOUT
 *
 *   images/
 *     real/        photographs taken by a human
 *     ai/          images generated by AI
 *     manifest.csv optional: filename,explanation
 *
 * The folder a file sits in IS its answer. Nothing else decides the label, so
 * a misfiled image is a wrong answer for every student who sees it — worth a
 * second pass before running this.
 *
 * Run:     node --env-file=.env.local scripts/load-images.mjs
 * Dry run: node --env-file=.env.local scripts/load-images.mjs --dry
 */
import { createClient } from '@supabase/supabase-js';
import { readFileSync, readdirSync, existsSync, statSync } from 'node:fs';
import { join, extname, basename } from 'node:path';

const URL_ = process.env.NEXT_PUBLIC_SUPABASE_URL;
const SERVICE = process.env.SUPABASE_SERVICE_ROLE_KEY;

const RED = '\x1b[31m', GREEN = '\x1b[32m', YELLOW = '\x1b[33m', CYAN = '\x1b[36m',
      DIM = '\x1b[2m', BOLD = '\x1b[1m', RESET = '\x1b[0m';

const DRY = process.argv.includes('--dry');
const ROOT = join(process.cwd(), 'images');
const MAX_BYTES = 250 * 1024;   // beyond this, venue wifi starts to hurt
const MIN_EDGE = 512;           // below this, images look like mush on a phone
const MIME = { '.webp': 'image/webp', '.jpg': 'image/jpeg', '.jpeg': 'image/jpeg', '.png': 'image/png' };

if (!URL_ || !SERVICE) {
  console.error(`${RED}Missing Supabase environment variables.${RESET}`);
  process.exit(1);
}

if (!existsSync(ROOT)) {
  console.log(`\n  ${YELLOW}No images/ folder found.${RESET}\n`);
  console.log(`  Create this structure next to package.json:\n`);
  console.log(`    ${CYAN}images/real/${RESET}   human photographs`);
  console.log(`    ${CYAN}images/ai/${RESET}     AI-generated images\n`);
  console.log(`  Then run this again.\n`);
  process.exit(1);
}

const admin = createClient(URL_, SERVICE, { auth: { persistSession: false } });

console.log(`\n  ${BOLD}Round 1 image loader${RESET}${DRY ? `  ${YELLOW}(dry run)${RESET}` : ''}\n`);

// ---------------------------------------------------------------------------
// Optional explanations. These are the single most valuable piece of content
// in the whole game — the giveaway detail a student screenshots and remembers.
// ---------------------------------------------------------------------------
const explanations = new Map();
const manifestPath = join(ROOT, 'manifest.csv');

if (existsSync(manifestPath)) {
  const rows = readFileSync(manifestPath, 'utf8').split('\n').filter((l) => l.trim());
  for (const row of rows) {
    // filename,explanation  — explanation may itself contain commas
    const comma = row.indexOf(',');
    if (comma < 1) continue;
    const name = row.slice(0, comma).trim();
    const text = row.slice(comma + 1).trim().replace(/^"|"$/g, '');
    if (name.toLowerCase() === 'filename') continue;
    explanations.set(name, text);
  }
  console.log(`  ${DIM}manifest.csv: ${explanations.size} explanations${RESET}\n`);
}

// ---------------------------------------------------------------------------
// Gather and validate
// ---------------------------------------------------------------------------
/**
 * Reads pixel dimensions straight from the file header — no image library.
 *
 * This exists because ML datasets are often tiny. CIFAKE, one of the most
 * downloaded real-vs-AI datasets, is 32x32. Those are fine for training a
 * classifier and useless for asking a human to judge on a phone screen.
 * Checking 400 images by eye is not realistic, so it happens here.
 */
function dimensions(path) {
  let fd;
  try {
    const buf = readFileSync(path);

    // PNG: width/height are big-endian uint32 at bytes 16 and 20.
    if (buf.length > 24 && buf[0] === 0x89 && buf[1] === 0x50) {
      return { w: buf.readUInt32BE(16), h: buf.readUInt32BE(20) };
    }

    // WebP (VP8X / VP8L / VP8 ) — RIFF container.
    if (buf.length > 30 && buf.toString('ascii', 0, 4) === 'RIFF') {
      const fourcc = buf.toString('ascii', 12, 16);
      if (fourcc === 'VP8X') {
        return {
          w: 1 + (buf.readUIntLE(24, 3) & 0xffffff),
          h: 1 + (buf.readUIntLE(27, 3) & 0xffffff),
        };
      }
      if (fourcc === 'VP8 ') {
        return { w: buf.readUInt16LE(26) & 0x3fff, h: buf.readUInt16LE(28) & 0x3fff };
      }
      if (fourcc === 'VP8L') {
        const bits = buf.readUInt32LE(21);
        return { w: (bits & 0x3fff) + 1, h: ((bits >> 14) & 0x3fff) + 1 };
      }
    }

    // JPEG: walk the markers to the first Start-Of-Frame.
    if (buf.length > 4 && buf[0] === 0xff && buf[1] === 0xd8) {
      let i = 2;
      while (i < buf.length - 9) {
        if (buf[i] !== 0xff) { i++; continue; }
        const marker = buf[i + 1];
        // SOF0..SOF3, SOF5..SOF7, SOF9..SOF11, SOF13..SOF15
        if (
          (marker >= 0xc0 && marker <= 0xc3) ||
          (marker >= 0xc5 && marker <= 0xc7) ||
          (marker >= 0xc9 && marker <= 0xcb) ||
          (marker >= 0xcd && marker <= 0xcf)
        ) {
          return { h: buf.readUInt16BE(i + 5), w: buf.readUInt16BE(i + 7) };
        }
        i += 2 + buf.readUInt16BE(i + 2);
      }
    }
  } catch {
    // Unreadable header is reported as unknown rather than crashing the run.
  }
  return null;
}

function gather(folder, label) {
  const dir = join(ROOT, folder);
  if (!existsSync(dir)) return [];

  return readdirSync(dir)
    .filter((f) => MIME[extname(f).toLowerCase()])
    .map((f) => {
      const path = join(dir, f);
      return {
        file: f,
        path,
        label,
        bytes: statSync(path).size,
        dim: dimensions(path),
        mime: MIME[extname(f).toLowerCase()],
        explanation: explanations.get(f) ?? null,
      };
    });
}

const items = [...gather('real', 'real'), ...gather('ai', 'ai_generated')];

if (items.length === 0) {
  console.log(`  ${RED}No images found in images/real or images/ai${RESET}\n`);
  process.exit(1);
}

const realCount = items.filter((i) => i.label === 'real').length;
const aiCount = items.filter((i) => i.label === 'ai_generated').length;
const oversize = items.filter((i) => i.bytes > MAX_BYTES);
const noExplanation = items.filter((i) => !i.explanation);

console.log(`  ${BOLD}Found${RESET}`);
console.log(`    real           ${realCount}`);
console.log(`    ai_generated   ${aiCount}`);
console.log(`    total          ${items.length}\n`);

let blocked = false;

if (realCount === 0 || aiCount === 0) {
  console.log(`  ${RED}FAIL${RESET}  Need at least one image in EACH folder.`);
  console.log(`        Every game shows one real and one AI image minimum.\n`);
  blocked = true;
}

if (items.length < 4) {
  console.log(`  ${RED}FAIL${RESET}  Need at least 4 active images; a game shows 4.\n`);
  blocked = true;
}

// Balance matters: a lopsided bank lets students guess the majority label.
const skew = Math.abs(realCount - aiCount) / items.length;
if (skew > 0.3) {
  console.log(`  ${YELLOW}WARN${RESET}  Bank is lopsided (${realCount} real vs ${aiCount} AI).`);
  console.log(`        Students who notice will just guess the common one.\n`);
}

if (items.length < 40) {
  console.log(`  ${YELLOW}WARN${RESET}  ${items.length} images. Four are shown per game, so`);
  console.log(`        neighbours will often see the same ones. Aim for 40+.\n`);
}

// ---- Resolution -------------------------------------------------------
const tooSmall = items.filter((i) => i.dim && Math.min(i.dim.w, i.dim.h) < MIN_EDGE);
const unknownDim = items.filter((i) => !i.dim);

if (items.length > 0) {
  const known = items.filter((i) => i.dim);
  if (known.length > 0) {
    const edges = known.map((i) => Math.min(i.dim.w, i.dim.h)).sort((a, b) => a - b);
    const median = edges[Math.floor(edges.length / 2)];
    console.log(`  ${DIM}shortest edge: min ${edges[0]}px, median ${median}px, max ${edges[edges.length - 1]}px${RESET}\n`);
  }
}

if (tooSmall.length > 0) {
  const worst = Math.min(...tooSmall.map((i) => Math.min(i.dim.w, i.dim.h)));

  // Below ~128px this is not a judgement call, the round simply does not work.
  if (worst < 128) {
    console.log(`  ${RED}FAIL${RESET}  ${tooSmall.length} image(s) under ${MIN_EDGE}px, smallest is ${worst}px.`);
    console.log(`        At ${worst}px these are unreadable on a phone. Students would be`);
    console.log(`        guessing at blurry squares, not judging AI images.`);
    console.log(`        Many ML datasets (CIFAKE is 32x32) are built for training,`);
    console.log(`        not for human judgement. Find a higher-resolution set.\n`);
    blocked = true;
  } else {
    console.log(`  ${YELLOW}WARN${RESET}  ${tooSmall.length} image(s) under ${MIN_EDGE}px on the short edge.`);
    console.log(`        Smallest is ${worst}px. These will look soft full-screen.\n`);
  }
}

if (unknownDim.length > 0) {
  console.log(`  ${YELLOW}WARN${RESET}  Could not read dimensions for ${unknownDim.length} file(s).\n`);
}

if (oversize.length > 0) {
  console.log(`  ${YELLOW}WARN${RESET}  ${oversize.length} image(s) over 250KB:`);
  for (const i of oversize.slice(0, 5)) {
    console.log(`        ${i.file}  ${(i.bytes / 1024).toFixed(0)}KB`);
  }
  console.log(`        Four of these per game on venue wifi is a stalled round.`);
  console.log(`        Convert to WebP at ~1200px wide before loading.\n`);
}

if (noExplanation.length > 0) {
  // Deliberately low-key. Explanations are NEVER shown during the competition
  // (§11 keeps Round 1 answers secret while entries are open), so a bank with
  // none still runs a perfectly fair event. They matter afterwards, for the
  // reveal and any follow-up session. Writing 400 is not a good use of the
  // last week; writing 30 good ones is.
  console.log(`  ${DIM}note  ${noExplanation.length} image(s) have no explanation.`);
  console.log(`        Not needed for the fair — explanations are only shown after`);
  console.log(`        entries close. Worth writing for 30-40 of the best ones.\n`);
}

if (blocked) {
  console.log(`  ${RED}Fix the failures above and run again.${RESET}\n`);
  process.exit(1);
}

if (DRY) {
  console.log(`  ${DIM}Dry run — nothing uploaded. Remove --dry to load.${RESET}\n`);
  process.exit(0);
}

// ---------------------------------------------------------------------------
// Upload
// ---------------------------------------------------------------------------
console.log(`  ${BOLD}Uploading${RESET}`);

let uploaded = 0;
let skipped = 0;
let failed = 0;

for (const item of items) {
  const stem = basename(item.file, extname(item.file)).replace(/[^a-zA-Z0-9_-]/g, '_');
  const key = `${item.label}/${stem}${extname(item.file).toLowerCase()}`;
  const publicUrl = `${URL_}/storage/v1/object/public/round1/${key}`;

  // Already loaded? Skip, so re-running after adding a few images is safe.
  const { data: existing } = await admin
    .from('round1_images')
    .select('id')
    .eq('storage_path', publicUrl)
    .maybeSingle();

  if (existing) {
    skipped++;
    continue;
  }

  const bytes = readFileSync(item.path);
  const { error: upErr } = await admin.storage
    .from('round1')
    .upload(key, bytes, { contentType: item.mime, upsert: true });

  if (upErr) {
    console.log(`    ${RED}fail${RESET} ${item.file} — ${upErr.message}`);
    failed++;
    continue;
  }

  const { error: dbErr } = await admin.from('round1_images').insert({
    storage_path: publicUrl,
    label: item.label,
    explanation: item.explanation,
    source_note: `loaded from images/${item.label === 'real' ? 'real' : 'ai'}/${item.file}`,
    active: true,
    is_test: false,
  });

  if (dbErr) {
    console.log(`    ${RED}fail${RESET} ${item.file} — ${dbErr.message}`);
    failed++;
    continue;
  }

  uploaded++;
  process.stdout.write(`\r    ${uploaded} uploaded…`);
}

console.log(`\n`);
console.log(`  ${GREEN}${uploaded} uploaded${RESET}   ${DIM}${skipped} already present${RESET}   ${failed ? RED : DIM}${failed} failed${RESET}\n`);

// ---------------------------------------------------------------------------
// Report the resulting bank, including any placeholders still live
// ---------------------------------------------------------------------------
const { data: health } = await admin.rpc('round1_bank_health');

if (health) {
  console.log(`  ${BOLD}Bank now${RESET}`);
  console.log(`    active         ${health.active}`);
  console.log(`    real / ai      ${health.real} / ${health.ai}`);
  console.log(`    playable       ${health.playable ? `${GREEN}yes${RESET}` : `${RED}no${RESET}`}`);

  if (health.placeholders > 0) {
    console.log(`\n  ${YELLOW}${health.placeholders} placeholder images are still live.${RESET}`);
    console.log(`  Real students would be shown them. Clear with:`);
    console.log(`    ${CYAN}node --env-file=.env.local scripts/seed-dev.mjs --clear${RESET}`);
  }
  if (health.missing_explanation > 0) {
    console.log(`\n  ${YELLOW}${health.missing_explanation} active images have no explanation.${RESET}`);
  }
}

console.log('');
