'use client';

import React, { useState } from 'react';
import Link from 'next/link';
import { Round1 } from '@/components/game/Round1';
import { Round2 } from '@/components/game/Round2';
import { Round3 } from '@/components/game/Round3';
import { Result } from '@/components/game/Result';
import { Interstitial, ROUND_INTROS, ROUND_OUTROS } from '@/components/game/Interstitial';
import { DashboardClient } from '@/components/dashboard/DashboardClient';
import type { Round1Slot, Round2Assignment, Round3Assignment, PublicAttemptResult } from '@/types';

type ScreenTab = 'stadium' | 'round1' | 'round2' | 'round3' | 'humanwin' | 'aiwin' | 'intro';

const mockSlots: Round1Slot[] = [
  {
    slot: 1,
    imageId: 'img-1',
    storagePath: '/sprites/flank-meadow-left.png',
    answered: false,
  },
  {
    slot: 2,
    imageId: 'img-2',
    storagePath: '/sprites/flank-circuit-right.png',
    answered: false,
  },
  {
    slot: 3,
    imageId: 'img-3',
    storagePath: '/sprites/bg-mobile-circuit.png',
    answered: false,
  },
];

const mockRound2: Round2Assignment = {
  classKey: 'apple',
  displayName: 'Apple',
  submitted: false,
};

const mockRound3: Round3Assignment = {
  prompt: 'What % of daily global internet traffic is generated by automated bots?',
  minValue: 0,
  maxValue: 100,
  step: 1,
  unit: '%',
  answered: false,
};

const mockHumanWin: PublicAttemptResult = {
  attemptId: 'preview-human-win',
  totalScore: 840,
  humanWin: true,
  rank: 1,
  percentileBeaten: 95,
  totalPlayers: 142,
};

const mockAiWin: PublicAttemptResult = {
  attemptId: 'preview-ai-win',
  totalScore: 420,
  humanWin: false,
  rank: 92,
  percentileBeaten: 28,
  totalPlayers: 142,
};

export default function PreviewPlayground() {
  const [activeTab, setActiveTab] = useState<ScreenTab>('stadium');
  const [key, setKey] = useState(0);

  const switchTab = (tab: ScreenTab) => {
    setActiveTab(tab);
    setKey((k) => k + 1);
  };

  return (
    <div className="min-h-dvh bg-[#02050e] text-white">
      {/* Top Floating Tab Switcher */}
      <div className="sticky top-0 z-50 flex flex-wrap items-center justify-center gap-2 border-b border-cyan-500/30 bg-[#050b1e]/95 px-3 py-2.5 backdrop-blur-md shadow-lg">
        <span className="font-pixel text-[10px] text-amber-300 uppercase mr-2 hidden sm:inline">
          UI SHOWCASE:
        </span>

        <button
          onClick={() => switchTab('stadium')}
          className={`rounded-lg px-2.5 py-1.5 font-display text-xs font-bold transition-all ${
            activeTab === 'stadium'
              ? 'bg-amber-500 text-black shadow-[0_0_10px_rgba(245,158,11,0.5)]'
              : 'border border-slate-700 bg-slate-800 text-slate-300 hover:border-slate-500'
          }`}
        >
          🏟️ Stadium
        </button>

        <button
          onClick={() => switchTab('round1')}
          className={`rounded-lg px-2.5 py-1.5 font-display text-xs font-bold transition-all ${
            activeTab === 'round1'
              ? 'bg-amber-500 text-black shadow-[0_0_10px_rgba(245,158,11,0.5)]'
              : 'border border-slate-700 bg-slate-800 text-slate-300 hover:border-slate-500'
          }`}
        >
          🎮 Round 1
        </button>

        <button
          onClick={() => switchTab('round2')}
          className={`rounded-lg px-2.5 py-1.5 font-display text-xs font-bold transition-all ${
            activeTab === 'round2'
              ? 'bg-cyan-500 text-black shadow-[0_0_10px_rgba(0,240,255,0.5)]'
              : 'border border-slate-700 bg-slate-800 text-slate-300 hover:border-slate-500'
          }`}
        >
          🎨 Round 2
        </button>

        <button
          onClick={() => switchTab('round3')}
          className={`rounded-lg px-2.5 py-1.5 font-display text-xs font-bold transition-all ${
            activeTab === 'round3'
              ? 'bg-cyan-500 text-black shadow-[0_0_10px_rgba(0,240,255,0.5)]'
              : 'border border-slate-700 bg-slate-800 text-slate-300 hover:border-slate-500'
          }`}
        >
          🧠 Round 3
        </button>

        <button
          onClick={() => switchTab('humanwin')}
          className={`rounded-lg px-2.5 py-1.5 font-display text-xs font-bold transition-all ${
            activeTab === 'humanwin'
              ? 'bg-emerald-500 text-black shadow-[0_0_10px_rgba(16,185,129,0.5)]'
              : 'border border-slate-700 bg-slate-800 text-slate-300 hover:border-slate-500'
          }`}
        >
          ★ Human Win
        </button>

        <button
          onClick={() => switchTab('aiwin')}
          className={`rounded-lg px-2.5 py-1.5 font-display text-xs font-bold transition-all ${
            activeTab === 'aiwin'
              ? 'bg-rose-500 text-white shadow-[0_0_10px_rgba(244,63,94,0.5)]'
              : 'border border-slate-700 bg-slate-800 text-slate-300 hover:border-slate-500'
          }`}
        >
          ⚡ AI Win
        </button>

        <button
          onClick={() => switchTab('intro')}
          className={`rounded-lg px-2.5 py-1.5 font-display text-xs font-bold transition-all ${
            activeTab === 'intro'
              ? 'bg-sky-500 text-black shadow-[0_0_10px_rgba(56,189,248,0.5)]'
              : 'border border-slate-700 bg-slate-800 text-slate-300 hover:border-slate-500'
          }`}
        >
          📜 Briefing
        </button>

        <Link
          href="/sprites/preview.html"
          target="_blank"
          className="rounded-lg border border-purple-500/50 bg-purple-950/50 px-2.5 py-1.5 font-display text-xs font-bold text-purple-300 hover:bg-purple-900/50 ml-2"
        >
          🖼️ All Sprites
        </Link>
      </div>

      {/* Screen Container */}
      <div key={key}>
        {activeTab === 'stadium' && (
          <DashboardClient
            initialClash={{
              humanTotal: 24500,
              aiTotal: 19800,
              humanPercentage: 55,
              aiPercentage: 45,
            }}
            initialEventStats={{
              totalPlayers: 142,
              humanWins: 78,
              aiWins: 64,
              topScore: 940,
              averageScore: 685,
              playingNow: 6,
            }}
            initialChallengers={[
              { rank: 1, displayName: 'Aisha M. (Engineering)', maskedIdSuffix: '2084', totalScore: 940 },
              { rank: 2, displayName: 'Omar K. (Computer Sci)', maskedIdSuffix: '1193', totalScore: 910 },
              { rank: 3, displayName: 'Fatima Z. (Dentistry)', maskedIdSuffix: '4452', totalScore: 890 },
              { rank: 4, displayName: 'Hamad S. (Business)', maskedIdSuffix: '8831', totalScore: 860 },
              { rank: 5, displayName: 'Reem A. (Pharmacy)', maskedIdSuffix: '7209', totalScore: 840 },
            ]}
          />
        )}

        {activeTab === 'round1' && (
          <Round1
            attemptId="preview-round-1"
            slots={mockSlots}
            msPerImage={8000}
            onComplete={() => alert('Round 1 Complete! Click another tab at the top to preview next.')}
          />
        )}

        {activeTab === 'round2' && (
          <Round2
            attemptId="preview-round-2"
            assignment={mockRound2}
            drawMs={20000}
            onComplete={() => alert('Round 2 Complete! Click another tab at the top to preview next.')}
          />
        )}

        {activeTab === 'round3' && (
          <Round3
            attemptId="preview-round-3"
            assignment={mockRound3}
            durationMs={8000}
            onComplete={() => alert('Round 3 Complete! Click another tab at the top to preview next.')}
          />
        )}

        {activeTab === 'humanwin' && <Result result={mockHumanWin} />}

        {activeTab === 'aiwin' && <Result result={mockAiWin} />}

        {activeTab === 'intro' && (
          <Interstitial
            intro={ROUND_INTROS[1]}
            seconds={10}
            timerValue={8}
            onDone={() => switchTab('round1')}
          />
        )}
      </div>
    </div>
  );
}
