'use client';
import type { ReactNode } from 'react';
export function Screen({children}:{children:ReactNode}){return <main className="relative flex min-h-dvh flex-col overflow-hidden bg-[var(--color-px-bg)]"><div className="arena-bg" aria-hidden="true"/><div className="relative z-10 mx-auto flex w-full max-w-md flex-1 flex-col px-5 py-7">{children}</div></main>}
export function Title({children}:{children:ReactNode}){return <h2 className="px-title-yellow text-lg uppercase leading-[1.8]">{children}</h2>}
export function Hint({children}:{children:ReactNode}){return <p className="mt-4 text-xs leading-relaxed text-slate-300">{children}</p>}
export function Button({children,onClick,disabled,busy,variant='primary',type='button'}:{children:ReactNode;onClick?:()=>void;disabled?:boolean;busy?:boolean;variant?:'primary'|'ghost';type?:'button'|'submit'}){return <button type={type} onClick={onClick} disabled={disabled||busy} className={`px-btn w-full min-h-[56px] px-6 py-4 text-xs ${variant==='primary'?'px-btn-yellow':'px-btn-ghost'}`} aria-busy={busy}>{busy?'Working…':children}</button>}
export function ErrorBanner({message,refCode}:{message:string;refCode?:string}){if(!message)return null;return <div role="alert" className="mt-5 border-[3px] border-[var(--color-px-ink)] bg-[#3d0f1d] px-4 py-3 shadow-[0_4px_0_var(--color-px-ink)]"><p className="text-xs font-semibold leading-relaxed text-[#ffb3bd]">{message}</p>{refCode&&<p className="mt-1 font-mono text-[10px] text-slate-400">{refCode}</p>}</div>}
export function Spacer(){return <div className="flex-1"/>}
export function RetryNotice({message,refCode,retryable,onRetry,busy}:{message:string;refCode?:string;retryable:boolean;onRetry:()=>void;busy?:boolean}){return <div><ErrorBanner message={message} refCode={refCode}/><div className="mt-3"><Button variant="ghost" busy={busy} onClick={retryable?onRetry:()=>window.location.reload()}>{retryable?'Try again':'Reload'}</Button></div></div>}
